baseURL: "https://chiayuhsu.github.io/children_song/"
languageCode: "en-us"
theme: "contrast-hugo"
publishDir: "docs"

params:
  sidebar: false
  fontawesome: true
  description: 'Made by <a href="">Blog Author</a>'

menu:
  main:
  - identifier: "home"
    name: "兒歌列表"
    url: "/"
    weight: 1
    pre: "<span class='fas fa-home hidden'></span>"
