baseURL: "https://chiayuhsu.github.io/children_song/"
languageCode: "en-us"
theme: "contrast-hugo"
publishDir: "docs"

params:
  sidebar: false
  fontawesome: true
  description: 'Made by <a href="">Blog Author</a>'

menu:
  main:
  - identifier: "home"
    name: "普通兒歌"
    url: "/"
    weight: 1

  - identifier: "learning"
    name: "學習兒歌"
    url: "/learning/"
    weight: 2

  - identifier: "story"
    name: "講故事"
    url: "/story/"
    weight: 3

  - identifier: "new"
    name: "新歌和新故事"
    url: "/new/"
    weight: 4
