baseURL: "https://chiayuhsu.github.io/children_song/"
languageCode: "en-us"
theme: "contrast-hugo"
publishDir: "docs"

params:
  sidebar: false
  fontawesome: true
  description: 'Made by <a href="">Blog Author</a>'

menu:
  main:
  - identifier: "home"
    name: "普通兒歌"
    url: "/"
    weight: 1

  - identifier: "learning"
    name: "學習兒歌"
    url: "/learning/"
    weight: 2

  - identifier: "baebaelife"
    name: "貝貝生活故事"
    url: "/baelife/"
    weight: 3
